import React from "react";
import Foo from "./foo"
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Đang chờ nhập input! :<",
  description: "Generated by your mom",
};

export default function Page() {

  return(
    <>
      <Foo />
    </>
  )
}