import type { Metadata } from "next";
import localFont from "next/font/local";
import "../assessts/css/reset.css";
import Nav from "./nav";
import style from "@/assessts/css/layout.module.scss"

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  // title: "loading...",
  description: "Generated by your mom",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
      <body>
        <header>
          <Nav />
        </header>

        <section className={style.section}>
          {children}
        </section>
      </body>
    </html>
  );
}
