import Image from "next/image";
// import { initializeApp } from "firebase/app";
import { useEffect, useState } from "react";
import Nav from "./nav";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Home",
  description: "Generated by your mom",
};

export default async function Home() {

  return (
    <>
      {/* <input type="text" /> */}
    </>
  );
}
